# UI configuration (symbols, keys, separators) for default locale
# Encoding of this file is UTF-8

marker.empty=\u0020
# Marker characters: ← → ◀ ▶ < > █ » ← ↑ ↓ [ ] ❯ ❯❯ ▸ ▸▸ ▸▸▸
marker.left=❯
marker.right=
multichoice.marker.unselected=[ ]
multichoice.marker.selected=[x]
dialog.option.disabled_suffix=\u0020(disabled)

navigationtoolbar.key_arrows_vertical=↑↓
navigationtoolbar.key_arrows_horizontal=◀ ▶
navigationtoolbar.key_space=Space
navigationtoolbar.key_enter=↵
navigationtoolbar.key_escape=Esc

navigationtoolbar.sep_item=\u0020|\u0020
navigationtoolbar.sep_hotkeylabel=\u0020

# Border definitions
# Borders examples:
#  ┌───────┐ ╔───────╗ ╔═══════╗
#  │       │ │       │ ║       ║
#  └───────┘ ╚───────╝ ╚═══════╝
border.no=\u0020

border.double.horizontal=═
border.double.vertical=║
border.double.top.left=╔
border.double.top.right=╗
border.double.bottom.left=╚
border.double.bottom.right=╝

border.single.horizontal=─
border.single.vertical=│
border.single.top.left=┌
border.single.top.right=┐
border.single.bottom.left=└
border.single.bottom.right=┘
