# UI Configuration (Symbols, keys, separators)
# Encoding of this file is UTF-8

marker.empty=\u0020
# Arrows characters: ← → ◀ ▶ < > █ » ← ↑ ↓ [ ] ❯ ❯❯ ▸ ▸▸ ▸▸▸
marker.left=❯
marker.right=

navigationtoolbar.key_arrows=↑↓
navigationtoolbar.key_enter=↵
navigationtoolbar.key_escape=Esc

navigationtoolbar.sep_item=\u0020|\u0020
navigationtoolbar.sep_hotkeylabel=\u0020
